import React from 'react'
import './Event.css'

function Event() {
  return (
    <div><b>Event</b>
        <div>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora maxime, ipsa quia quo veritatis laborum aperiam nisi nostrum molestias blanditiis suscipit ipsam alias eius non nemo dolores autem voluptate. Deleniti porro in ipsa perspiciatis? Inventore nisi quo quam quos. Aliquam placeat sequi necessitatibus deserunt at maiores explicabo labore dolorum expedita eveniet et veniam consequuntur, maxime atque, accusantium saepe ipsa odit magnam quo unde quibusdam! Distinctio cum voluptates vitae ratione. Aut, et totam? Error aut delectus vel. Ex, quae molestias exercitationem facilis ea obcaecati dolorem, officia nihil, veniam deleniti veritatis maiores? Autem id beatae omnis! Esse nisi unde optio soluta non?</div>
        <div>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora maxime, ipsa quia quo veritatis laborum aperiam nisi nostrum molestias blanditiis suscipit ipsam alias eius non nemo dolores autem voluptate. Deleniti porro in ipsa perspiciatis? Inventore nisi quo quam quos. Aliquam placeat sequi necessitatibus deserunt at maiores explicabo labore dolorum expedita eveniet et veniam consequuntur, maxime atque, accusantium saepe ipsa odit magnam quo unde quibusdam! Distinctio cum voluptates vitae ratione. Aut, et totam? Error aut delectus vel. Ex, quae molestias exercitationem facilis ea obcaecati dolorem, officia nihil, veniam deleniti veritatis maiores? Autem id beatae omnis! Esse nisi unde optio soluta non?</div>
        <div>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora maxime, ipsa quia quo veritatis laborum aperiam nisi nostrum molestias blanditiis suscipit ipsam alias eius non nemo dolores autem voluptate. Deleniti porro in ipsa perspiciatis? Inventore nisi quo quam quos. Aliquam placeat sequi necessitatibus deserunt at maiores explicabo labore dolorum expedita eveniet et veniam consequuntur, maxime atque, accusantium saepe ipsa odit magnam quo unde quibusdam! Distinctio cum voluptates vitae ratione. Aut, et totam? Error aut delectus vel. Ex, quae molestias exercitationem facilis ea obcaecati dolorem, officia nihil, veniam deleniti veritatis maiores? Autem id beatae omnis! Esse nisi unde optio soluta non?</div>
        <div>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora maxime, ipsa quia quo veritatis laborum aperiam nisi nostrum molestias blanditiis suscipit ipsam alias eius non nemo dolores autem voluptate. Deleniti porro in ipsa perspiciatis? Inventore nisi quo quam quos. Aliquam placeat sequi necessitatibus deserunt at maiores explicabo labore dolorum expedita eveniet et veniam consequuntur, maxime atque, accusantium saepe ipsa odit magnam quo unde quibusdam! Distinctio cum voluptates vitae ratione. Aut, et totam? Error aut delectus vel. Ex, quae molestias exercitationem facilis ea obcaecati dolorem, officia nihil, veniam deleniti veritatis maiores? Autem id beatae omnis! Esse nisi unde optio soluta non?</div>
        <div>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora maxime, ipsa quia quo veritatis laborum aperiam nisi nostrum molestias blanditiis suscipit ipsam alias eius non nemo dolores autem voluptate. Deleniti porro in ipsa perspiciatis? Inventore nisi quo quam quos. Aliquam placeat sequi necessitatibus deserunt at maiores explicabo labore dolorum expedita eveniet et veniam consequuntur, maxime atque, accusantium saepe ipsa odit magnam quo unde quibusdam! Distinctio cum voluptates vitae ratione. Aut, et totam? Error aut delectus vel. Ex, quae molestias exercitationem facilis ea obcaecati dolorem, officia nihil, veniam deleniti veritatis maiores? Autem id beatae omnis! Esse nisi unde optio soluta non?</div>
    </div>
  )
}

export default Event