import React from 'react'
import './About.css'

function About() {
  return (
    <div id='about'>About
        <div>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Facilis ab eligendi quis quae dolorem quam esse ipsum eveniet rerum quo repudiandae vel, consequatur nihil recusandae nisi error vitae nulla voluptatem provident, necessitatibus, aliquam ex. Optio laudantium officiis ullam tenetur ipsa voluptatem recusandae, facilis maiores nostrum deserunt consectetur natus provident aperiam dolorem incidunt quidem quo et repellat nesciunt suscipit doloremque vel. Laboriosam, ratione consectetur accusamus similique atque, voluptates dolorem cumque ipsum deserunt itaque voluptate impedit obcaecati! Vel perferendis deserunt omnis animi, excepturi qui. Quidem dignissimos repudiandae commodi ullam quia consequatur incidunt fugit, minus porro dolorum dolor quam maiores in! Hic, ut.</div>
        <div>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Facilis ab eligendi quis quae dolorem quam esse ipsum eveniet rerum quo repudiandae vel, consequatur nihil recusandae nisi error vitae nulla voluptatem provident, necessitatibus, aliquam ex. Optio laudantium officiis ullam tenetur ipsa voluptatem recusandae, facilis maiores nostrum deserunt consectetur natus provident aperiam dolorem incidunt quidem quo et repellat nesciunt suscipit doloremque vel. Laboriosam, ratione consectetur accusamus similique atque, voluptates dolorem cumque ipsum deserunt itaque voluptate impedit obcaecati! Vel perferendis deserunt omnis animi, excepturi qui. Quidem dignissimos repudiandae commodi ullam quia consequatur incidunt fugit, minus porro dolorum dolor quam maiores in! Hic, ut.</div>
        <div>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Facilis ab eligendi quis quae dolorem quam esse ipsum eveniet rerum quo repudiandae vel, consequatur nihil recusandae nisi error vitae nulla voluptatem provident, necessitatibus, aliquam ex. Optio laudantium officiis ullam tenetur ipsa voluptatem recusandae, facilis maiores nostrum deserunt consectetur natus provident aperiam dolorem incidunt quidem quo et repellat nesciunt suscipit doloremque vel. Laboriosam, ratione consectetur accusamus similique atque, voluptates dolorem cumque ipsum deserunt itaque voluptate impedit obcaecati! Vel perferendis deserunt omnis animi, excepturi qui. Quidem dignissimos repudiandae commodi ullam quia consequatur incidunt fugit, minus porro dolorum dolor quam maiores in! Hic, ut.</div>
        <div>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Facilis ab eligendi quis quae dolorem quam esse ipsum eveniet rerum quo repudiandae vel, consequatur nihil recusandae nisi error vitae nulla voluptatem provident, necessitatibus, aliquam ex. Optio laudantium officiis ullam tenetur ipsa voluptatem recusandae, facilis maiores nostrum deserunt consectetur natus provident aperiam dolorem incidunt quidem quo et repellat nesciunt suscipit doloremque vel. Laboriosam, ratione consectetur accusamus similique atque, voluptates dolorem cumque ipsum deserunt itaque voluptate impedit obcaecati! Vel perferendis deserunt omnis animi, excepturi qui. Quidem dignissimos repudiandae commodi ullam quia consequatur incidunt fugit, minus porro dolorum dolor quam maiores in! Hic, ut.</div>
    </div>
  )
}

export default About